name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@65.2.69.97 "echo SSH SUCCESS"

      - name: Connect and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@65.2.69.97 << 'EOF'
          cd url-shortener
          git pull
          sudo docker-compose down
          sudo docker-compose up -d --build
          EOF
